version: '3'
services:
  #Adminer
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=mancave
    networks:
      - app-network

  #MySQL Service
  db:
    image: library/mariadb:10.5.6
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laurel.cms
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=random
      - MYSQL_PASSWORD=secret
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  #PHP Service
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - DB_HOST=db
    volumes:
      - ../:/var/www/html/Laurel/CMS
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ../:/var/www/html/Laurel/CMS
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #Supervisor
  supervisor:
    build:
      context: .
      dockerfile: supervisord.dockerfile
    restart: unless-stopped
    ports:
      - 9001:9001
    environment:
      - DB_HOST=db
    networks:
      - app-network
    volumes_from:
      - app

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
